#Contributors: Will Chronister, Inusah Diallo
#2019-09-06

#Plots beds generated by bedtools genomecov earlier in step4
#Plots all CNVs together and separated by del and dup, for each of 3 thresholds

# setwd("~/r_script_tests")
#Our (slightly modified) version of a function by Sacha Epskamp for checking for the presence of a package and installing if absent.
#http://stackoverflow.com/questions/9341635/how-can-i-check-for-installed-r-packages-before-running-install-packages
pkgTestBC <- function(x){
        if(!require(x,character.only=TRUE)){
                source("http://bioconductor.org/biocLite.R")
                biocLite(x)
                if(!require(x,character.only=TRUE)) stop("Package not found")
        }
}

pkgTest <- function(x){
        if(!require(x,character.only=TRUE)){
                install.packages(x)
                if(!require(x,character.only=TRUE)) stop("Package not found")
        }
}
pkgTest("dplyr")
pkgTest("ggplot2")
pkgTest("tidyr")
pkgTest("MASS")

library(dplyr)
library(ggplot2)
#turn off scientific notation
options(scipen = 999)
#turn off stringsAsFactors
options(stringsAsFactors = FALSE)
args <- commandArgs(trailing=T)

directorys<- args[1]
fin <- args[2]

dirtable <- read.table(directorys)

dirtable_vector <- dirtable[,1]

dir_name <- dirtable_vector[1]
for(thresh in c("new_thresholds","lenient_thresholds","stringent_thresholds")){
  
  dirthresh <- paste(fin,"/cnv_results/",thresh,"/",sep="")

  CNV_genomecovs <- list.files(dirthresh, pattern = "cnvs_genomecov.bed", full.names = T)

#  directory <- "uva-PoolJuly2018_iGenomxRiptide_mouse_p53KOmouse3"
  directory <- paste(dir_name)
  rundir <- basename(directory)
  run <- strsplit(rundir,split="_")[[1]][1]
  wga <- strsplit(rundir,split="_")[[1]][2]
  species <- strsplit(rundir,split="_")[[1]][3]
  indivname <- strsplit(rundir,split="_")[[1]][4]
  #chromosomes <- read.table("~/r_script_tests/human.hg19.ONLY_chr1_to_chrY.genome")
  if(species=="human"){
    chrXnum <- 23
    chrYnum <- 24
    chromosomes <- read.table("/nv/vol97/mcconnell_lab/cnvpipe/software/bedtools-2.17.0/genomes/human.hg19.ONLY_chr1_to_chr22.genome")
    chromosomes[,2:3] <- cbind(1,chromosomes$V2)
    chromosomes$V1 <- gsub("chrX",chrXnum,chromosomes$V1)
    chromosomes$V1 <- gsub("chrY",chrYnum,chromosomes$V1)
    chromosomes$V1 <- as.integer(gsub("chr","",chromosomes$V1))
    chromosomes <- chromosomes %>% arrange(V1, V2, V3)
  } else if(species=="mouse"){
    chrXnum <- 20
    chrYnum <- 21
    #chromosomes <- read.table("./cnv_results/lenient_thresholds/mouse.mm9.ONLY_chr1_to_chrY.genome")
    chromosomes <- read.table("/nv/vol97/mcconnell_lab/cnvpipe/software/bedtools-2.17.0/genomes/mouse.mm9.ONLY_chr1_to_chr19.genome")
    chromosomes[,2:3] <- cbind(1,chromosomes$V2)
    chromosomes$V1 <- gsub("chrX",chrXnum,chromosomes$V1)
    chromosomes$V1 <- gsub("chrY",chrYnum,chromosomes$V1)
    chromosomes$V1 <- as.integer(gsub("chr","",chromosomes$V1))
    chromosomes <- chromosomes %>% arrange(V1, V2, V3)
  }

  chr1pos <- mean(c(chromosomes$V3[1],chromosomes$V2[1]))
  chr3pos <- mean(c(chromosomes$V3[3],chromosomes$V2[3])) + sum(chromosomes$V3[1:2])
  chr5pos <- mean(c(chromosomes$V3[5],chromosomes$V2[5])) + sum(chromosomes$V3[1:4])
  chr7pos <- mean(c(chromosomes$V3[7],chromosomes$V2[7])) + sum(chromosomes$V3[1:6])
  chr9pos <- mean(c(chromosomes$V3[9],chromosomes$V2[9])) + sum(chromosomes$V3[1:8])
  chr11pos <- mean(c(chromosomes$V3[11],chromosomes$V2[11])) + sum(chromosomes$V3[1:10])
  chr13pos <- mean(c(chromosomes$V3[13],chromosomes$V2[13])) + sum(chromosomes$V3[1:12])
  chr15pos <- mean(c(chromosomes$V3[15],chromosomes$V2[15])) + sum(as.numeric(chromosomes$V3[1:14]))
  chr17pos <- mean(c(chromosomes$V3[17],chromosomes$V2[17])) + sum(as.numeric(chromosomes$V3[1:16]))
  chr19pos <- mean(c(chromosomes$V3[19],chromosomes$V2[19])) + sum(as.numeric(chromosomes$V3[1:18]))
  chrpositions <- c(chr1pos, chr3pos, chr5pos, chr7pos, chr9pos,
                    chr11pos, chr13pos, chr15pos, chr17pos, chr19pos)
  if(species=="human"){
    chr21pos <- mean(c(chromosomes$V3[21],chromosomes$V2[21])) + sum(as.numeric(chromosomes$V3[1:20]))
    chrpositions <- c(chrpositions, chr21pos)
  }
  # genomecovs <- list.files(pattern = "01_cnvs_genomecov.bed")
  # genomecovs <- genomecovs[!(grepl("del",genomecovs))]
  # genomecovs <- genomecovs[!(grepl("dup",genomecovs))]

  for(i in 1:(length(CNV_genomecovs))){
    indivname <- strsplit(basename(CNV_genomecovs[i]),"_cnvs_")[[1]][1]
    cnvs_genomecov <- read.table(CNV_genomecovs[i])
    if(file.exists(paste(dirthresh,indivname,"_dels_genomecov.bed",sep=""))){
      dels_genomecov <- read.table(paste(dirthresh,indivname,"_dels_genomecov.bed",sep="")) 
    } else {
      dels_genomecov <- chromosomes[1:(chrXnum-1),]
      dels_genomecov <- cbind(dels_genomecov, 0)
    }
    if(file.exists( paste(dirthresh,indivname,"_dups_genomecov.bed",sep="") )){
      dups_genomecov <- read.table(paste(dirthresh,indivname,"_dups_genomecov.bed",sep=""))
    } else {
      dups_genomecov <- chromosomes[1:(chrXnum-1),]
      dups_genomecov <- cbind(dups_genomecov, 0)
    }

    cnvs_genomecov[,1] <- as.numeric(gsub("chr","", cnvs_genomecov[,1]))
    dels_genomecov[,1] <- as.numeric(gsub("chr","", dels_genomecov[,1]))
    dups_genomecov[,1] <- as.numeric(gsub("chr","", dups_genomecov[,1]))
    colnames(cnvs_genomecov) <- c("Chr","Start","End","Number_of_CNVs")
    colnames(dels_genomecov) <- c("Chr","Start","End","Number_of_CNVs")
    colnames(dups_genomecov) <- c("Chr","Start","End","Number_of_CNVs")

    total_Mb_cnvs_cov <- sum(as.numeric(cnvs_genomecov$Number_of_CNVs *
                        (cnvs_genomecov$End - cnvs_genomecov$Start))) / 1000000
    total_Mb_dels_cov <- sum(as.numeric(dels_genomecov$Number_of_CNVs *
                                          (dels_genomecov$End - dels_genomecov$Start))) / 1000000
    total_Mb_dups_cov <- sum(as.numeric(dups_genomecov$Number_of_CNVs *
                                          (dups_genomecov$End - dups_genomecov$Start))) / 1000000

    for(chrom in 1:(chrXnum-1)){
      if(nrow(subset(cnvs_genomecov,Chr==chrom))==0){
        insert_row <- data.frame("Chr"=chrom,"Start"=0,End=chromosomes[chrom,3],
                                 "Number_of_CNVs"=0)
        cnvs_genomecov <- rbind(cnvs_genomecov, insert_row)
      }
      if(nrow(subset(dels_genomecov,Chr==chrom))==0){
        insert_row <- data.frame("Chr"=chrom,"Start"=0,End=chromosomes[chrom,3],
                                 "Number_of_CNVs"=0)
        dels_genomecov <- rbind(dels_genomecov, insert_row)
      }
      if(nrow(subset(dups_genomecov,Chr==chrom)) ==0){
        insert_row <- data.frame("Chr"=chrom,"Start"=0,End=chromosomes[chrom,3],
                                 "Number_of_CNVs"=0)
        dups_genomecov <- rbind(dups_genomecov, insert_row)
      }
    }

    cnvs_genomecov <- cnvs_genomecov %>% arrange(Chr, Start, End)
    dels_genomecov <- dels_genomecov %>% arrange(Chr, Start, End)
    dups_genomecov <- dups_genomecov %>% arrange(Chr, Start, End)


    lastval <- 0
    lastval2 <- 0
    lastval3 <- 0
    newpos <- c()
    newpos2 <- c()
    newpos3 <- c()
    for(y in 1:(chrXnum-1)){
      temp_table <- subset(cnvs_genomecov, Chr==y)
      fixpos <- temp_table$End + lastval
      lastval <- fixpos[length(fixpos)]
      newpos<-c(newpos,fixpos)

      temp_table2 <- subset(dels_genomecov, Chr==y)
      fixpos2 <- temp_table2$End + lastval2
      lastval2 <- fixpos2[length(fixpos2)]
      newpos2<-c(newpos2,fixpos2)

      temp_table3 <- subset(dups_genomecov, Chr==y)
      fixpos3 <- temp_table3$End + lastval3
      lastval3 <- fixpos3[length(fixpos3)]
      newpos3<-c(newpos3,fixpos3)
    }
    cnvs_genomecov$Position <- newpos
    dels_genomecov$Position <- newpos2
    dups_genomecov$Position <- newpos3

    #Add a row for each start and end of segment (doubles nrow of dataframe)
    expanded_cnvs_genomecov <- data.frame()
    for(row in 1:nrow(cnvs_genomecov)){
      line <- cnvs_genomecov[row,]
      new_line <- line
      new_line$Position <- line$Position-(new_line$End-new_line$Start)
      expanded_cnvs_genomecov <- rbind(expanded_cnvs_genomecov, new_line, line)
    }
    expanded_dels_genomecov <- data.frame()
    for(row in 1:nrow(dels_genomecov)){
      line <- dels_genomecov[row,]
      new_line <- line
      new_line$Position <- line$Position-(new_line$End-new_line$Start)
      expanded_dels_genomecov <- rbind(expanded_dels_genomecov, new_line, line)
    }
    expanded_dups_genomecov <- data.frame()
    for(row in 1:nrow(dups_genomecov)){
      line <- dups_genomecov[row,]
      new_line <- line
      new_line$Position <- line$Position-(new_line$End-new_line$Start)
      expanded_dups_genomecov <- rbind(expanded_dups_genomecov, new_line, line)
    }

    #Code for adding rows at 0 CNVs for beginning and end of chromosome -- decided against this
#    for(chr in 1:(chrXnum-1)){
#      firstrow <- expanded_cnvs_genomecov %>% filter(Chr==chr) %>% slice(1)
#      lastrow <- expanded_cnvs_genomecov %>% filter(Chr==chr) %>% slice(n())
#      firstrow$Number_of_CNVs <- 0
#      lastrow$Number_of_CNVs <- 0
#      expanded_cnvs_genomecov <- rbind(expanded_cnvs_genomecov, firstrow, lastrow)
#    }
#    expanded_cnvs_genomecov <- arrange(Chr, Position, Number_of_CNVs)


    ggplot(data = expanded_cnvs_genomecov,
           mapping=aes(x=Position, y=Number_of_CNVs,# group=Chr,
                       color=as.factor(Chr))) +
      scale_color_manual(values=rep(c("red1","blue1"),11)) +
      scale_x_continuous(breaks = chrpositions,
                         labels = as.character(seq(1,2*length(chrpositions)-1,2)),
                         expand = c(0,0)) +
      xlab("Chromosome") +
      ylim(0,max(expanded_cnvs_genomecov$Number_of_CNVs)) +
      geom_vline(xintercept = c(cumsum(chromosomes$V3[1:(nrow(chromosomes)-2)])),
                 color="gray80") +
      geom_line(size=0.8) +
      theme_bw(base_size = 18) +
      theme(legend.position="none",panel.grid.minor.x = element_blank(), panel.grid.major.x = element_blank()) +
      ggtitle(paste(indivname," CNV coverage (", round(total_Mb_cnvs_cov,0)," Mb)",sep=""))
    ggsave(paste(dirthresh,indivname,"_cnv_coverage.png",sep=""), height=7, width=14)

    write.table(expanded_cnvs_genomecov, file = paste(dirthresh, indivname,"_",thresh, "_cnv_coverage_plot_table.txt",sep=""),
                sep="\t",col.names=T,row.names=F,quote=F)



    expanded_dels_genomecov$CNV_type <- "del"
    expanded_dels_genomecov$Number_of_CNVs <- -(expanded_dels_genomecov$Number_of_CNVs)
    expanded_dups_genomecov$CNV_type <- "dup"
    combined_dups_dels_genomecov <- rbind(expanded_dels_genomecov,expanded_dups_genomecov)

    ggplot(combined_dups_dels_genomecov, aes(x=Position, y=Number_of_CNVs,
                                             color=CNV_type)) +
      geom_vline(xintercept = c(cumsum(chromosomes$V3[1:(nrow(chromosomes)-2)])),
                 color="gray80") +
      geom_line(size=0.8) +
      scale_color_manual(values=c("red","green2")) +
      xlab("Chromosome") + ylab("CNVs (dup. positive, del. negative)") +
      ylim(min(combined_dups_dels_genomecov$Number_of_CNVs),max(combined_dups_dels_genomecov$Number_of_CNVs)) +
      theme_bw(base_size = 18) +
      theme(legend.position="none",panel.grid.minor.x = element_blank(),panel.grid.major.x = element_blank()) +
      ggtitle(paste(indivname," CNV coverage (",round(total_Mb_dels_cov,0)," del Mb, ",round(total_Mb_dups_cov,0)," dup Mb)",sep="")) +
      scale_x_continuous(breaks = chrpositions,
                         labels = as.character(seq(1,2*length(chrpositions)-1,2)),
                         expand = c(0,0))
    ggsave(paste(dirthresh,indivname,"_cnv_coverage_SPLIT_dup_del.png",sep=""), height=7, width=14)

    write.table(combined_dups_dels_genomecov, file = paste(dirthresh, indivname,"_",thresh, "_SPLIT_dup_del_coverage_plot_table.txt",sep=""),
                sep="\t",col.names=T,row.names=F,quote=F)

  }

}






# #Get BED files for any peaks covering <20% of the genome
# genomecovs <- list.files(pattern = "genomecov.bed")
# pct_coverages <- c()
# names <- c()
# for(j in 1:length(genomecovs)){
#   covbed <- read.table(genomecovs[j])
#   if(grepl("_01_",genomecovs[j])){
#     threshold <- "01"
#   } else {
#     threshold <- "05"
#   }
#   grpname <- strsplit(genomecovs[j],"_0")[[1]][1]
#   colnames(covbed) <- c("Chr","Start","End","Number_of_CNVs")
#   covbed$Chr <- as.numeric(gsub("chr","", covbed$Chr))
#   for(chrom in 1:22){
#     if(nrow(subset(covbed,Chr==chrom))==0){
#       insert_row <- data.frame("Chr"=chrom,"Start"=0,"End"=chromosomes[chrom,3],
#                                "Number_of_CNVs"=0)
#       covbed <- rbind(covbed, insert_row)
#     }
#   }
#   covbed <- covbed %>% arrange(Chr, Start, End)
#   max_CNVs <- max(covbed$Number_of_CNVs)
#   for(k in 1:max_CNVs){
#     tempcovbed <- covbed
#     tempcovbed$past_threshold <- tempcovbed$Number_of_CNVs >= k
#     fixed_tempcovbed <- data.frame()
#     for(t in 1:22){
#       temptemp <- tempcovbed %>% filter(Chr==t)
#       if(nrow(temptemp) == 1){
#         new <- temptemp[1,c(1,2,3,5)]
#         fixed_tempcovbed <- rbind(fixed_tempcovbed, new)
#         colnames(fixed_tempcovbed) <- c("Chr","Start","End","past_threshold")
#       } else {
#         rles <- rle(temptemp$past_threshold)
#         rles$cumsum <- cumsum(rles$lengths)
#         startrow <- 1
#         for(y in 1:length(rles$lengths)){
#           endrow <- rles$cumsum[y]
#           new <- c(temptemp$Chr[startrow], temptemp$Start[startrow],temptemp$End[endrow],temptemp$past_threshold[startrow])
#           fixed_tempcovbed <- rbind(fixed_tempcovbed, new)
#           colnames(fixed_tempcovbed) <- c("Chr","Start","End","past_threshold")
#           startrow <- endrow + 1
#         }
#       }
#     }
#
#     bed_to_save <- fixed_tempcovbed %>% filter(past_threshold == T) %>% select(Chr, Start, End)
#     total_bp_coverage <- sum(as.numeric(bed_to_save$End - bed_to_save$Start))
#     pct_coverage <- total_bp_coverage/sum(as.numeric(chromosomes$V3[1:22]))
#     pct_coverages <- c(pct_coverages, pct_coverage)
#     names <- c(names, paste(threshold,"_",grpname,"_",k,"ormore_cnvs.bed",sep=""))
#     if(pct_coverage < 0.2){
#       write.table(bed_to_save, paste(threshold,"_",grpname,"_",k,"ormore_cnvs.bed",sep=""), sep="\t",row.names = F,col.names = F)
#     }
#   }
# #  for(k in 0:max_CNVs){
#   #Only look at regions with 0 CNVs, not 0-1, 0-2, etc. (10/16/17 change)
#   for(k in 0){
#     tempcovbed <- covbed
#     tempcovbed$past_threshold <- tempcovbed$Number_of_CNVs <= k
#     fixed_tempcovbed <- data.frame()
#     for(t in 1:22){
#       temptemp <- tempcovbed %>% filter(Chr==t)
#       if(nrow(temptemp) == 1){
#         new <- temptemp[1,c(1,2,3,5)]
#         fixed_tempcovbed <- rbind(fixed_tempcovbed, new)
#         colnames(fixed_tempcovbed) <- c("Chr","Start","End","past_threshold")
#       } else {
#         rles <- rle(temptemp$past_threshold)
#         rles$cumsum <- cumsum(rles$lengths)
#         startrow <- 1
#         for(y in 1:length(rles$lengths)){
#           endrow <- rles$cumsum[y]
#           new <- c(temptemp$Chr[startrow], temptemp$Start[startrow],temptemp$End[endrow],temptemp$past_threshold[startrow])
#           fixed_tempcovbed <- rbind(fixed_tempcovbed, new)
#           colnames(fixed_tempcovbed) <- c("Chr","Start","End","past_threshold")
#           startrow <- endrow + 1
#         }
#       }
#     }
#
#     bed_to_save <- fixed_tempcovbed %>% filter(past_threshold == T) %>% select(Chr, Start, End)
#     total_bp_coverage <- sum(as.numeric(bed_to_save$End - bed_to_save$Start))
#     pct_coverage <- total_bp_coverage/sum(as.numeric(chromosomes$V3[1:22]))
#     pct_coverages <- c(pct_coverages, pct_coverage)
#     names <- c(names, paste(threshold,"_",grpname,"_",k,"orfewer_cnvs.bed",sep=""))
#     if(pct_coverage < 0.3){
#       # write.table(bed_to_save, paste(threshold,"_",grpname,"_",k,"orfewer_cnvs.bed",sep=""), sep="\t",row.names = F,col.names = F)
#       write.table(bed_to_save, paste(threshold,"_",grpname,"_",k,"_cnvs.bed",sep=""), sep="\t",row.names = F,col.names = F)
#     }
#   }
# }
#
# coverage_table <- as.data.frame(cbind(names, pct_coverages))
